### ISSUE TITLE
Hitting the enter key after an entry

### ISSUE THREAD

**Issue by bocciaman** [ahmadassaf/alfred-workflow-fantastical#5]
Is it normal functionality to hit the enter key and the workflow opens Fantastical? But Not complete the entry into the calendar? So you must hit enter again?

**Comment by giovannicoppola** [comment]
@bocciaman I think the idea is to give you a chance to check that the parsing was correct. If you want to add directly by default, you can add `with add immediately` to the applescript, so that it reads `tell application "Fantastical" to parse sentence "{query}" with add immediately`

**Comment by bocciaman** [comment]
Thank you!
